# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x0btic_tac_toe\"\x19\n\x17RequestCurrentGameboard\"6\n\x18ResponseCurrentGameboard\x12\x1a\n\x12updated_game_field\x18\x01 \x01(\t\"D\n\rPlayerRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"E\n\x0ePlayerResponse\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\xb5\x01\n\rPlayerService\x12G\n\nset_symbol\x12\x1a.tic_tac_toe.PlayerRequest\x1a\x1b.tic_tac_toe.PlayerResponse\"\x00\x12[\n\nlist_board\x12$.tic_tac_toe.RequestCurrentGameboard\x1a%.tic_tac_toe.ResponseCurrentGameboard\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCURRENTGAMEBOARD._serialized_start=27
  _REQUESTCURRENTGAMEBOARD._serialized_end=52
  _RESPONSECURRENTGAMEBOARD._serialized_start=54
  _RESPONSECURRENTGAMEBOARD._serialized_end=108
  _PLAYERREQUEST._serialized_start=110
  _PLAYERREQUEST._serialized_end=178
  _PLAYERRESPONSE._serialized_start=180
  _PLAYERRESPONSE._serialized_end=249
  _PLAYERSERVICE._serialized_start=252
  _PLAYERSERVICE._serialized_end=433
# @@protoc_insertion_point(module_scope)
