# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x0btic_tac_toe\"I\n\x07Message\x12\x0e\n\x06origin\x18\x01 \x01(\x05\x12\x0e\n\x06max_id\x18\x02 \x01(\x05\x12\x0e\n\x06rounds\x18\x03 \x01(\x05\x12\x0e\n\x06leader\x18\x04 \x01(\x05\"\x19\n\x17RequestCurrentGameboard\"6\n\x18ResponseCurrentGameboard\x12\x1a\n\x12updated_game_field\x18\x01 \x01(\t\"D\n\rPlayerRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\x80\x01\n\x0ePlayerResponse\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x39\n\ngame_board\x18\x04 \x01(\x0b\x32%.tic_tac_toe.ResponseCurrentGameboard2\xf2\x01\n\rPlayerService\x12G\n\nset_symbol\x12\x1a.tic_tac_toe.PlayerRequest\x1a\x1b.tic_tac_toe.PlayerResponse\"\x00\x12[\n\nlist_board\x12$.tic_tac_toe.RequestCurrentGameboard\x1a%.tic_tac_toe.ResponseCurrentGameboard\"\x00\x12;\n\x0bPassMessage\x12\x14.tic_tac_toe.Message\x1a\x14.tic_tac_toe.Message\"\x00\x32\xb4\x01\n\x0c\x41\x64minService\x12G\n\nset_symbol\x12\x1a.tic_tac_toe.PlayerRequest\x1a\x1b.tic_tac_toe.PlayerResponse\"\x00\x12[\n\nlist_board\x12$.tic_tac_toe.RequestCurrentGameboard\x1a%.tic_tac_toe.ResponseCurrentGameboard\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=27
  _MESSAGE._serialized_end=100
  _REQUESTCURRENTGAMEBOARD._serialized_start=102
  _REQUESTCURRENTGAMEBOARD._serialized_end=127
  _RESPONSECURRENTGAMEBOARD._serialized_start=129
  _RESPONSECURRENTGAMEBOARD._serialized_end=183
  _PLAYERREQUEST._serialized_start=185
  _PLAYERREQUEST._serialized_end=253
  _PLAYERRESPONSE._serialized_start=256
  _PLAYERRESPONSE._serialized_end=384
  _PLAYERSERVICE._serialized_start=387
  _PLAYERSERVICE._serialized_end=629
  _ADMINSERVICE._serialized_start=632
  _ADMINSERVICE._serialized_end=812
# @@protoc_insertion_point(module_scope)
