# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class PlayerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set_symbol = channel.unary_unary(
                '/tic_tac_toe.PlayerService/set_symbol',
                request_serializer=game__pb2.PlayerRequest.SerializeToString,
                response_deserializer=game__pb2.PlayerResponse.FromString,
                )
        self.list_board = channel.unary_unary(
                '/tic_tac_toe.PlayerService/list_board',
                request_serializer=game__pb2.RequestCurrentGameboard.SerializeToString,
                response_deserializer=game__pb2.ResponseCurrentGameboard.FromString,
                )


class PlayerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set_symbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list_board(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set_symbol': grpc.unary_unary_rpc_method_handler(
                    servicer.set_symbol,
                    request_deserializer=game__pb2.PlayerRequest.FromString,
                    response_serializer=game__pb2.PlayerResponse.SerializeToString,
            ),
            'list_board': grpc.unary_unary_rpc_method_handler(
                    servicer.list_board,
                    request_deserializer=game__pb2.RequestCurrentGameboard.FromString,
                    response_serializer=game__pb2.ResponseCurrentGameboard.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tic_tac_toe.PlayerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlayerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set_symbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tic_tac_toe.PlayerService/set_symbol',
            game__pb2.PlayerRequest.SerializeToString,
            game__pb2.PlayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def list_board(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tic_tac_toe.PlayerService/list_board',
            game__pb2.RequestCurrentGameboard.SerializeToString,
            game__pb2.ResponseCurrentGameboard.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
