# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alicia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61licia.proto\"b\n\x13\x45\x64itDistanceRequest\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\x12\x0e\n\x06leader\x18\x02 \x01(\x05\x12\x12\n\nfirst_word\x18\x03 \x01(\t\x12\x13\n\x0bsecond_word\x18\x04 \x01(\t\"(\n\x14\x45\x64itDistanceResponse\x12\x10\n\x08\x64istance\x18\x01 \x01(\x05\"I\n\x07Message\x12\x0e\n\x06origin\x18\x01 \x01(\x05\x12\x0e\n\x06max_id\x18\x02 \x01(\x05\x12\x0e\n\x06rounds\x18\x03 \x01(\x05\x12\x0e\n\x06leader\x18\x04 \x01(\x05\"\x1c\n\x0cTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\x03\"$\n\x0eTimeAdjustment\x12\x12\n\nadjustment\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty2T\n\x13\x45\x64itDistanceService\x12=\n\x0c\x45\x64itDistance\x12\x14.EditDistanceRequest\x1a\x15.EditDistanceResponse\"\x00\x32\x35\n\x0cRingElection\x12%\n\rStartElection\x12\x08.Message\x1a\x08.Message\"\x00\x32j\n\x17\x42\x65rkeleySynchronization\x12&\n\x0bRequestTime\x12\x06.Empty\x1a\r.TimeResponse\"\x00\x12\'\n\nAdjustTime\x12\x0f.TimeAdjustment\x1a\x06.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alicia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EDITDISTANCEREQUEST._serialized_start=16
  _EDITDISTANCEREQUEST._serialized_end=114
  _EDITDISTANCERESPONSE._serialized_start=116
  _EDITDISTANCERESPONSE._serialized_end=156
  _MESSAGE._serialized_start=158
  _MESSAGE._serialized_end=231
  _TIMERESPONSE._serialized_start=233
  _TIMERESPONSE._serialized_end=261
  _TIMEADJUSTMENT._serialized_start=263
  _TIMEADJUSTMENT._serialized_end=299
  _EMPTY._serialized_start=301
  _EMPTY._serialized_end=308
  _EDITDISTANCESERVICE._serialized_start=310
  _EDITDISTANCESERVICE._serialized_end=394
  _RINGELECTION._serialized_start=396
  _RINGELECTION._serialized_end=449
  _BERKELEYSYNCHRONIZATION._serialized_start=451
  _BERKELEYSYNCHRONIZATION._serialized_end=557
# @@protoc_insertion_point(module_scope)
