# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Berkeley.berkeley_pb2 as berkeley__pb2


class BerkeleySynchronizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTime = channel.unary_unary(
                '/tic_tac_toe.BerkeleySynchronization/RequestTime',
                request_serializer=berkeley__pb2.Empty.SerializeToString,
                response_deserializer=berkeley__pb2.TimeResponse.FromString,
                )
        self.AdjustTime = channel.unary_unary(
                '/tic_tac_toe.BerkeleySynchronization/AdjustTime',
                request_serializer=berkeley__pb2.TimeAdjustment.SerializeToString,
                response_deserializer=berkeley__pb2.Empty.FromString,
                )


class BerkeleySynchronizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BerkeleySynchronizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTime': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTime,
                    request_deserializer=berkeley__pb2.Empty.FromString,
                    response_serializer=berkeley__pb2.TimeResponse.SerializeToString,
            ),
            'AdjustTime': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustTime,
                    request_deserializer=berkeley__pb2.TimeAdjustment.FromString,
                    response_serializer=berkeley__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tic_tac_toe.BerkeleySynchronization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BerkeleySynchronization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tic_tac_toe.BerkeleySynchronization/RequestTime',
            berkeley__pb2.Empty.SerializeToString,
            berkeley__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdjustTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tic_tac_toe.BerkeleySynchronization/AdjustTime',
            berkeley__pb2.TimeAdjustment.SerializeToString,
            berkeley__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
